config/routes.rb
Rails.application.routes.draw do
  get "subjects/index"
  get "semesters/index"
  root "home#index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "up" => "rails/health#show", as: :rails_health_check
  get "/home", to: "home#index"
  get "signup", to: "users#new"
  resources :users, except: [ :new ]
  get "login",  to: "sessions#new"
  post "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "semesters", to: "semesters#index"
  post "semesters", to: "semesters#create"
  get "subjects", to: "subjects#index"
  post "subjects", to: "subjects#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/semester.rb
class Semester < ApplicationRecord
  belongs_to :user
  has_many :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :semester
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :semesters, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 1. Start the bouncer here (this applies to the whole app)
  before_action :require_user

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to do that"
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_user, only: [ :index ]
  def index
    # render the page
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
def index
  @semesters = current_user.semesters
  @semester = current_user.semesters.build
end

def create
@semester = current_user.semesters.build(semester_params)
if @semester.active?
  puts "True"
  current_user.semesters.update_all(active: false)
  @semesters = current_user.semesters
end
  if @semester.save
    redirect_to semesters_path, notice: "Semester created successfully."
  else
    render :index, status: :unprocessable_entity
  end
end

private
  def semester_params
    params.require(:semester).permit(:name, :active, :number)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [ :new, :create ]
  def new
    # just to render the login form
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      puts "user authenticated"
      session[:user_id] = user.id # This "logs in" the user by saving their ID in a cookie
      redirect_to home_path, notice: "Logged in successfully!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil # This "logs out" the user by clearing the cookie
    redirect_to root_path, notice: "Logged out successfully!"
    # puts "User logged out"
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @semesters = current_user.semesters
    @current_semester = @semesters.find_by(active: true)
    @subjects = @current_semester.subjects
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
     if @subject.save
      redirect_to subjects_path, notice: "Semester created successfully."
     else
      render :index, status: :unprocessable_entity
     end
  end

private
  def subject_params
    params.require(:subject).permit(:name, :semester_id, :credits, :professor, :subject_code)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new # Just an empty object to build the form
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: "Signup successful! Please log in."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :college)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_dashboard.html.erb
<div class="dashboard">
  <h1>Welcome back, <%= current_user.username %>!</h1>
  <div class="stats"></div>
  <%= button_to "Log Out", logout_path, method: :delete, class: "logout-btn" %>
  <%= link_to "Manage Semesters", semesters_path, class: "button-style" %>
  <%= link_to "Manage Subjects", subjects_path, class: "button-style" %>
</div>

app/views/home/_landing_page.html.erb
<div class="hero">
  <h1>Welcome to College Planner</h1>
  <p>Track your assignments and exams with ease.</p>
  <%= link_to "Sign Up", signup_path, class: "btn" %>
  <%= link_to "Login", login_path, class: "btn" %>
</div>

app/views/home/index.html.erb
<% if logged_in? %>
  <%= render "dashboard" %>
<% else %>
  <%= render "landing_page" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "College Planner" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |type, message| %>
  <div class="flash-message <%= type %>">
    <%= message %>
  </div>
<% end %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/semesters/index.html.erb
<h1>My Semesters</h1>
<section class="semester-form">
  <h3>Add New Semester</h3>
  <%= form_with model: @semester do |f| %>
    <div>
      <%= f.label :name, "Semester Name (e.g. Fall 2025)" %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :number, "Semester Number (e.g. 1, 2, 3)" %>
      <%= f.text_field :number %>
    </div>
    <div>
      <%= f.label :active, "Set as Current Semester?" %>
      <%= f.check_box :active %>
    </div>
    <%= f.submit "Create Semester" %>
  <% end %>
</section>
<hr>
<section class="semester-list">
  <h3>Existing Semesters</h3>
  <ul>
    <% @semesters.each do |semester| %>
      <li>
        <%= semester.name %>
        <%= "(Current)" if semester.active %>
      </li>
    <% end %>
  </ul>
</section>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subjects/index.html.erb
<section class="subject-form">
  <h3>Add New Subject</h3>
  <%= form_with model: @subject do |f| %>
    <%= f.label :Name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :Code %>
    <%= f.text_field :subject_code %>
    <br>
    <%= f.label :Credits %>
    <%= f.text_field :credits %>
    <br>
     <%= f.label :Professor %>
    <%= f.text_field :professor %>
    <br>
    <%= f.label :semester_id, "Select Semester" %>
    <%= f.collection_select :semester_id, @semesters, :id, :name %>
    <br>
    <%= f.submit %>
  <% end %>
</section>
<section class="semester-list">
  <h3>Subjects of Each semester</h3>
  <ul>
    <% @semesters.each do |semester| %>
      <li>
        <%= semester.name %>
        <% semester.subjects.each do |subject| %>
          <ol>
            <%= subject.name %>
          </ol>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/form.html.erb
<h1>New product</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %><br>
    <%= form.label :email %><br>
    <%= form.email_field :email %><br>
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>
 <%# Use :password and password_field %>
    <%= form.label :college %><br>
    <%= form.text_field :college %><br>
  </div>
  <div>
    <%= form.submit "Create Account" %>
  </div>
<% end %>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %><br>
    <%= form.label :email %><br>
    <%= form.email_field :email %><br>
    <%= form.label :password %><br>
    <%= form.password_field :password %><br>
 <%# Use :password and password_field %>
    <%= form.label :college %><br>
    <%= form.text_field :college %><br>
  </div>
  <div>
    <%= form.submit "Create Account" %>
  </div>
<% end %>